/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.BlaBlaCarClient.InterfazUsuarioComun;

import com.mycompany.BlaBlaCarClient.BlaBlaCarProtocol.BlaBlaCarProtocol;
import com.mycompany.BlaBlaCarClient.ResultadoBusquedaReserva.DetalleViajeSeleccionado;
import com.mycompany.BlaBlaCarClient.UsuarioInterfaz.UserInterface;
import com.mycompany.blablacarclient.BlaBlaCarClient;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maite
 */
public class InterfazUsuarioComun extends javax.swing.JFrame {
    private final BlaBlaCarClient cliente;
    private final BlaBlaCarProtocol protocolo;
    
    private final DefaultTableModel tabla;
    private List<Viaje> viajes;
    /**
     * Creates new form InterfazUsuarioComun
     * @param cliente
     */
    public InterfazUsuarioComun(BlaBlaCarClient cliente) {
        initComponents();
        this.cliente = cliente;
        viajes = new ArrayList();
        
        tabla = (DefaultTableModel) this.jTableViajesEncontrados.getModel();
        tabla.setRowCount(0);
        
        protocolo = new BlaBlaCarProtocol();
        
        this.jButton1.setEnabled(false);
        
        this.jComboBoxOrigen.addItem(" ");
        this.jComboBoxOrigen.addItem("Granada");
        this.jComboBoxOrigen.addItem("Sevilla");
        this.jComboBoxOrigen.addItem("Alicante");
        this.jComboBoxOrigen.addItem("Jaén");
        
        this.jComboBoxDestino.addItem(" ");
        this.jComboBoxDestino.addItem("Sevilla");
        this.jComboBoxDestino.addItem("Granada");
        this.jComboBoxDestino.addItem("Madrid");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOrigen = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jLabelFechaLlegada = new javax.swing.JLabel();
        jLabelHoraLlegada = new javax.swing.JLabel();
        jTextFieldHoraLlegada = new javax.swing.JTextField();
        jLabelFechaSalida = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableViajesEncontrados = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelOrigen.setText("Origen");

        jLabelDestino.setText("Destino");

        jComboBoxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDestinoActionPerformed(evt);
            }
        });

        jLabelFechaLlegada.setText("Fecha Llegada");

        jLabelHoraLlegada.setText("Hora Llegada");

        jLabelFechaSalida.setText("Fecha Salida");

        jLabel6.setText("Hora Salida");

        jLabelPrecio.setText("Precio");

        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });

        jTableViajesEncontrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Origen", "Destino", "Fecha de salida", "Hora de salida", "Precio"
            }
        ));
        jTableViajesEncontrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableViajesEncontradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableViajesEncontrados);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButton1.setText("Detalles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar sesión");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelHoraLlegada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelFechaLlegada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelFechaSalida)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonBuscar)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrigen)
                    .addComponent(jLabelDestino)
                    .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelFechaLlegada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFechaSalida)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoraLlegada)
                    .addComponent(jTextFieldHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDestinoActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String[] filtros = new String[7];
        if(this.jComboBoxOrigen.getSelectedItem() != null)
            filtros[0] = this.jComboBoxOrigen.getSelectedItem().toString();
        else 
            filtros[0] = " ";
        
        if(this.jComboBoxDestino.getSelectedItem() != null)
            filtros[1] = this.jComboBoxDestino.getSelectedItem().toString();
        else
            filtros[1] = " ";
        
        if(this.jDateChooser1.getDate() != null)
            filtros[2] = sdf.format(this.jDateChooser1.getDate());
        else
            filtros[2] = " ";
        
        if(this.jTextField2.getText().equals(""))
            filtros[3] = " ";
        else
            filtros[3] = this.jTextField2.getText();
        
        if(this.jDateChooser2.getDate() != null)
            filtros[4] = sdf.format(this.jDateChooser2.getDate());
        else
            filtros[4]= " ";
        
        if(this.jTextFieldHoraLlegada.getText().equals(""))
            filtros[5] = " ";
        else
            filtros[5] = this.jTextFieldHoraLlegada.getText();
        
        if(this.jTextFieldPrecio.getText().equals(""))
            filtros[6] = " ";
        else
            filtros[6] = this.jTextFieldPrecio.getText();
        
        String[] mensajes = protocolo.realizarBusquedaViajesOfertados(filtros, cliente);
        mostrarViajesOfertados(mensajes);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableViajesEncontradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableViajesEncontradosMouseClicked
        this.jButton1.setEnabled(true);
    }//GEN-LAST:event_jTableViajesEncontradosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] infoViaje = new String[4];
        int i = this.jTableViajesEncontrados.getSelectedRow();
        
        infoViaje[0] = String.valueOf(viajes.get(i).getId_coche());
        infoViaje[1] = String.valueOf(viajes.get(i).getTrayecto().getId());
        infoViaje[2] = viajes.get(i).getFecha_salida();
        infoViaje[3] = viajes.get(i).getHora_salida();
        
        String[] mensajes = protocolo.obtenerDetallesViaje(infoViaje);
        byte[] foto = protocolo.obtenerFoto();
        if(mensajes[4].equals("GET_DETAIL_TRAVEL_CORRECT")) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(DetalleViajeSeleccionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(DetalleViajeSeleccionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(DetalleViajeSeleccionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(DetalleViajeSeleccionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new DetalleViajeSeleccionado(mensajes, foto, cliente, viajes.get(i)).setVisible(true);
                }
            });
        } else {
            JOptionPane.showMessageDialog(null, "No se han podido mostrar los detalles de este viaje");
        }
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        protocolo.cerrarSesion();
        dispose();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    public void mostrarViajesOfertados(String[] mensajes) {
        viajes = new ArrayList();
        tabla.setRowCount(0);
        if(mensajes[4].equals("GET_TRAVELS_CORRECT")) {
            String[] viajesS = new String[mensajes.length - 5], fila = new String[5];
            int k = 0;
            for(int i = 5; i < mensajes.length; i++) {
                viajesS[k] = mensajes[i];
                k++;
            }
            
            if(viajesS[0] == null) {
                this.noHayViajes();
            } else {
                int j = 1;
                int q = 0;
                viajes.add(new Viaje());
                viajes.get(q).setTrayecto(new Trayecto());
                for(int i = 0; i < viajesS.length; i++) {
                    if(j == 1) 
                        viajes.get(q).setId_coche(Integer.parseInt(viajesS[i]));
                    
                    if(j == 2) 
                        viajes.get(q).getTrayecto().setId(Integer.parseInt(viajesS[i]));
                        
                    if(j == 3) {
                        viajes.get(q).getTrayecto().setOrigen(viajesS[i]);
                        fila[0] = viajesS[i];
                    }
                    
                    if(j == 4) {
                        viajes.get(q).getTrayecto().setDestino(viajesS[i]);
                        fila[1] = viajesS[i];
                    }
                    
                    if(j == 5) {
                        viajes.get(q).setFecha_salida(viajesS[i]);
                        fila[2] = viajesS[i];
                    }
                    
                    if(j == 6) {
                        viajes.get(q).setHora_salida(viajesS[i]);
                        fila[3] = viajesS[i];
                    }

                    if(j == 7) {
                        float precio = Float.parseFloat(viajesS[i]);
                        BigDecimal precioBig = new BigDecimal(precio);
                        viajes.get(q).setPrecio(precioBig);

                        j = 0;
                        fila[4] = viajesS[i];
                        tabla.addRow(fila);
                        q++;
                        
                        viajes.add(new Viaje());
                        viajes.get(q).setTrayecto(new Trayecto());
                    }
                    j++;
                }
            }
        } else {
            error();
        }
    }
    
    public static void error() {
        JOptionPane.showMessageDialog(null, "El usuario no coincide con niguno que esté registrado");
    }
    
    public void noHayViajes() {
        JOptionPane.showMessageDialog(null, "No se han encontrado viajes con estos filtros");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxOrigen;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelFechaLlegada;
    private javax.swing.JLabel jLabelFechaSalida;
    private javax.swing.JLabel jLabelHoraLlegada;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableViajesEncontrados;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldHoraLlegada;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
